### ISSUE TITLE
Can't compile file on Windows

### ISSUE THREAD

**Issue by greenei** [lvdmaaten/bhtsne#43]
After following the steps in the readme the command window tells me:

sptree.cpp(111): error: c3861: 'fmax': identifier not found

**Comment by greenei** [comment]
It works on VS 14.0 instead of VS 11.0, maybe update readme?
